package testgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/lhaig/intent/internal/ast"
)

// GenerateIntent produces a `.intent` source file containing `test "..." { ... }`
// blocks generated from the contracts in the input program.
//
// Phase 16 / ADR 0029 task 16.8. This is the Intent-native counterpart to
// Generate (which emits Rust source). The Intent emission targets the
// `intentc test` runner introduced in task 16.7.
//
// `sourceImport` is the relative path used in the generated file's `import`
// declaration so the tests can call into the source module. Pass "" to skip
// the import (user must add it manually before running the tests).
//
// Scope:
//   - Standalone functions with Int parameters and at least one contract clause
//     emit a test that iterates the constrained Int range deterministically,
//     calls the function, and asserts each ensures clause's expression.
//   - Functions with parameters of other types (Float, String, Array, etc.),
//     or no parameters, fall back to a single example call.
//   - Entities and methods are documented as out-of-scope for the current
//     iteration; the existing Rust emission (Generate) still handles them.
//     A follow-up task lifts entity tests into Intent emission.
func GenerateIntent(prog *ast.Program, sourceImport string) string {
	var sb strings.Builder

	modName := "auto_tests"
	if prog.Module != nil && prog.Module.Name != "" {
		modName = prog.Module.Name + "_auto_tests"
	}
	sb.WriteString(fmt.Sprintf("module %s version \"1.0\";\n\n", modName))

	if sourceImport != "" {
		sb.WriteString(fmt.Sprintf("import %q;\n\n", sourceImport))
	}

	sb.WriteString("// Auto-generated by intentc test-gen --target intent.\n")
	sb.WriteString("// Do not edit by hand; regenerate when contracts change.\n//\n")
	if sourceImport != "" {
		sb.WriteString("// Note: functions and entities referenced here must be marked `public`\n")
		sb.WriteString("// in the source for the import to expose them. If you see a type-check\n")
		sb.WriteString("// error about an unknown function, add `public` in front of the\n")
		sb.WriteString("// `function`/`entity` keyword in the source file.\n//\n")
	}
	sb.WriteString("// Phase 16 scope: standalone functions with contracts only.\n")
	sb.WriteString("// Entities, methods, and complex parameter types are TODO.\n\n")

	emitted := 0
	for _, f := range prog.Functions {
		if f.IsEntry {
			continue
		}
		if len(f.Requires) == 0 && len(f.Ensures) == 0 {
			continue
		}
		block := generateIntentTestForFunction(f)
		if block != "" {
			sb.WriteString(block)
			sb.WriteString("\n")
			emitted++
		}
	}

	// Phase 16 scope cut: entities/methods deferred to follow-up. Note in
	// output so users know.
	if hasEntityWithContracts(prog) {
		sb.WriteString("// Entity / method auto-tests are not emitted by --target intent yet.\n")
		sb.WriteString("// Use `intentc test-gen` (Rust emission) for entity tests, or write\n")
		sb.WriteString("// hand-written tests against the entity constructor and methods.\n\n")
	}

	if emitted == 0 {
		sb.WriteString("// No contract-bearing standalone functions found to auto-test.\n")
	}

	// Tests require a callable entry function under the project's current
	// rules (the `intentc test` runner inherits the entry-point conventions
	// of `intentc build`).
	sb.WriteString("entry function main() returns Int { return 0; }\n")
	return sb.String()
}

func hasEntityWithContracts(prog *ast.Program) bool {
	for _, e := range prog.Entities {
		if len(e.Invariants) > 0 {
			return true
		}
		if e.Constructor != nil && (len(e.Constructor.Requires) > 0 || len(e.Constructor.Ensures) > 0) {
			return true
		}
		for _, m := range e.Methods {
			if len(m.Requires) > 0 || len(m.Ensures) > 0 {
				return true
			}
		}
	}
	return false
}

// generateIntentTestForFunction emits an Intent test block for a single
// standalone function. The strategy:
//
//   - All-Int params with derivable bounds: nested-or-zipped iteration over
//     the bounds, asserting each ensures clause.
//   - No params: single call, assert each ensures clause.
//   - Otherwise: a single example call with default values, asserting each
//     ensures clause. (Best-effort — real property tests for non-Int types
//     are a follow-up.)
func generateIntentTestForFunction(f *ast.FunctionDecl) string {
	// Sort params by name for deterministic output.
	params := make([]*ast.Param, len(f.Params))
	copy(params, f.Params)
	sort.SliceStable(params, func(i, j int) bool { return params[i].Name < params[j].Name })

	constraints := AnalyzeConstraints(params, f.Requires)
	allInt := allIntParams(params)

	hasResult := f.ReturnType != nil && f.ReturnType.Name != "Void"

	var sb strings.Builder
	testName := fmt.Sprintf("auto: %s contracts", f.Name)
	sb.WriteString(fmt.Sprintf("test %q {\n", testName))

	switch {
	case len(params) == 0:
		// One call, assert each ensures.
		if hasResult {
			sb.WriteString(fmt.Sprintf("    let __r: %s = %s();\n",
				typeRefToIntent(f.ReturnType), f.Name))
		} else {
			sb.WriteString(fmt.Sprintf("    %s();\n", f.Name))
		}
		emitEnsuresAsserts(&sb, f.Ensures, hasResult)

	case allInt && len(params) == 1:
		p := params[0]
		lo, hi := intRange(constraints[p.Name], -10, 10)
		// Cap range to keep generated tests fast.
		if hi-lo > 200 {
			hi = lo + 200
		}
		sb.WriteString(fmt.Sprintf("    let mutable %s: Int = %d;\n", p.Name, lo))
		sb.WriteString(fmt.Sprintf("    while %s <= %d {\n", p.Name, hi))
		emitPreconditionGuard(&sb, f.Requires, "        ")
		if hasResult {
			sb.WriteString(fmt.Sprintf("        let __r: %s = %s(%s);\n",
				typeRefToIntent(f.ReturnType), f.Name, p.Name))
		} else {
			sb.WriteString(fmt.Sprintf("        %s(%s);\n", f.Name, p.Name))
		}
		emitEnsuresAssertsIndented(&sb, f.Ensures, hasResult, "        ")
		sb.WriteString(fmt.Sprintf("        %s = %s + 1;\n", p.Name, p.Name))
		sb.WriteString("    }\n")

	default:
		// Fallback: example call with default values; assert ensures.
		args := defaultArgsForParams(params)
		if hasResult {
			sb.WriteString(fmt.Sprintf("    let __r: %s = %s(%s);\n",
				typeRefToIntent(f.ReturnType), f.Name, args))
		} else {
			sb.WriteString(fmt.Sprintf("    %s(%s);\n", f.Name, args))
		}
		emitEnsuresAsserts(&sb, f.Ensures, hasResult)
	}

	sb.WriteString("}\n")
	return sb.String()
}

func allIntParams(params []*ast.Param) bool {
	if len(params) == 0 {
		return false
	}
	for _, p := range params {
		if p.Type == nil || p.Type.Name != "Int" {
			return false
		}
	}
	return true
}

// intRange returns the iteration bounds for an Int-typed parameter, falling
// back to defaults if the constraint is unbounded.
func intRange(c *ParamConstraint, defaultLo, defaultHi int64) (int64, int64) {
	lo, hi := defaultLo, defaultHi
	if c != nil {
		if c.Lower != nil {
			lo = *c.Lower
		}
		if c.Upper != nil {
			hi = *c.Upper
		}
		if hi < lo {
			hi = lo + 10
		}
	}
	return lo, hi
}

func typeRefToIntent(t *ast.TypeRef) string {
	if t == nil {
		return "Void"
	}
	if len(t.TypeArgs) == 0 {
		return t.Name
	}
	args := make([]string, 0, len(t.TypeArgs))
	for _, a := range t.TypeArgs {
		args = append(args, typeRefToIntent(a))
	}
	return t.Name + "<" + strings.Join(args, ", ") + ">"
}

// emitPreconditionGuard wraps the body in an `if requires { ... }` block so
// that runs violating preconditions are skipped rather than crashing.
func emitPreconditionGuard(sb *strings.Builder, requires []*ast.ContractClause, indent string) {
	for _, req := range requires {
		// Use RawText since it's the original Intent source — no translation
		// needed.
		sb.WriteString(fmt.Sprintf("%sif not (%s) { continue; }\n", indent, req.RawText))
	}
}

func emitEnsuresAsserts(sb *strings.Builder, ensures []*ast.ContractClause, hasResult bool) {
	emitEnsuresAssertsIndented(sb, ensures, hasResult, "    ")
}

func emitEnsuresAssertsIndented(sb *strings.Builder, ensures []*ast.ContractClause, hasResult bool, indent string) {
	for _, ens := range ensures {
		expr := ens.RawText
		// `result` in the contract refers to the return value; map to __r in
		// the generated body.
		if hasResult {
			expr = strings.ReplaceAll(expr, "result", "__r")
		}
		sb.WriteString(fmt.Sprintf("%sassert(%s);\n", indent, expr))
	}
}

func defaultArgsForParams(params []*ast.Param) string {
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = defaultArgFor(p)
	}
	return strings.Join(parts, ", ")
}

func defaultArgFor(p *ast.Param) string {
	if p.Type == nil {
		return "0"
	}
	switch p.Type.Name {
	case "Int":
		return "1"
	case "Float":
		return "1.0"
	case "Bool":
		return "true"
	case "String":
		return "\"\""
	case "Array":
		// Empty array literal; element type inferred from declaration.
		return "[]"
	default:
		return "/* TODO: provide a value */"
	}
}
